services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-logger:
    image: localhost/redis-logger:latest
    depends_on:
      - postgres
      - redis
    entrypoint: ["python", "main.py"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres-data:
    driver: local
